### ISSUE TITLE
alpine events

### ISSUE THREAD

**Issue by HausemasterIssue** [Smokeybear12/HydraWare#2]
bloat, waste of time and dogshit, switch to forge events, they are built in, simpler and require less dependencies.

**Comment by Smokeybear12** [comment]
It was just a quick thing for a friend. Here is the original source: https://github.com/ItzMeBlaze/HydraWare-SRC

( The alpine event bus is roughly 70 percent faster than the forge event bus. The forge event bus, while built in, is quite laggy. It does support most of the things a normal user would want, but alpine is much quicker. For a project like this the forge event bus would work just fine. Really the perfect solution is to make your own event bus. )
